version: '3'

services:
  backend:
    build: backend/.
    ports:
      - "8080:8080"
    networks:
      - combine
  frontend:
    build: frontend/.
    ports:
      - "80:80"
    networks:
      - combine

networks:
  combine: